services:
  db:
    image: postgres:15
    env_file: ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2
    command: |
      caddy run --config /etc/Caddyfile
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
