services:
  db:
    image: postgres:15
    env_file: ./backend/.env
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2
    command: |
      caddy run --config - << 'EOF'
      localhost {
          # Frontend
          handle / {
              reverse_proxy frontend:3000
          }
          # Backend API
          handle /api/* {
              reverse_proxy backend:8000
          }
      }
      EOF
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
